name: slovogram
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  syncfusion_flutter_charts: ^19.4.48
  intl: ^0.17.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  hive_generator: ^1.1.1
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf

flutter_icons:
  android: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.png"